DROP TABLE IF EXISTS CARS;

CREATE TABLE CARS (
	Id SERIAL,
	"Model" VARCHAR(10),
	"Registration" VARCHAR(7),
	"Color" VARCHAR(15)
);

CREATE UNIQUE INDEX IDX_CARS_REGISTRATION ON CARS("Registration");